#!/bin/sh

. ~/scripts/tofi/config

entry=$(printf " poweroff\n   reboot\n exit\n  lock\n suspend" | tofi_full "power")
entry=$(echo $entry | cut -b5- )

if [ "$entry" = "poweroff" ] || [ "$entry" = "reboot" ]; then
    if [ "$(~/scripts/tofi/confirm "confirm")" = "yes" ]; then
        doas $entry
    fi
elif [ "$entry" = "lock" ]; then
    ~/scripts/lock-blur
elif [ "$entry" = "suspend" ]; then
    systemctl suspend
elif [ "$entry" = "exit" ]; then
    if [ "$(~/scripts/tofi/confirm "exit?")" = "yes" ]; then
        doas killall swhkd swhks
        wayland-logout
    fi
fi
